notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

install: true

addons:
  sonarcloud:
    organization: "statnlp"
    token:
      secure: $SONARCLOUD_TOKEN

language: java

jdk:
  - oraclejdk8

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./mvnw package -DskipTests=true
  - bash script/Dockerbuild.sh

before_deploy:
  - ./mvnw javadoc:javadoc
  - cp -a site/. target/site/

deploy:
  local-dir: target/site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: service-negationscope.statnlp.org
  on:
    branch: master

after_deploy:
    - bash script/Dockerpush.sh
